### ISSUE TITLE
Drop dependency on rmapshaper?

### ISSUE THREAD

**Issue by nuntius35** [PatrickStotz/2019-02-tempolimit#2]
I am using Arch linux and even after spending a lot of time compiling stuff, I was unable to get rmapshaper working. Of course, that's not your fault. Still I want to suggest, that you drop the dependency on rmapshaper by distributing preprocessed simplified geometries for clipping. I don't think it's really necessary to do that on the fly. In this way you would make the project more accessible for people who quickly want to try out the code.

**Comment by PatrickStotz** [comment]
True, getting rmapshaper up and running might be an unnecessary obstacle.
Since I want to work with unaltered public data, I've now switched to the more simplified data set by BKG.

**Comment by nuntius35** [comment]
Thanks, that's a great change. I had one little issue with this: at least under Linux filenames are case sensitive. In line 110 I had to change the filename from `VG2500_LAN.shp` to `vg2500_lan.shp`.

**Comment by PatrickStotz** [comment]
Thanks for spotting. Fixed it now
